name: Deploy Container with Bind Mount

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Pull latest image
        run: docker pull arijitacn/mywebapp:latest

      - name: Remove old container
        shell: powershell
        run: |
          if (docker ps -a --format "{{.Names}}" | Select-String "mywebapp-container") {
           docker rm -f mywebapp-container
          }

      - name: Run container with bind mount
        run: |
          docker run -d `
          --name mywebapp-container `
          -p 3000:3000 `
          -v C:\docker-bind-data:/app/data `
          arijitacn/mywebapp:latest
        shell: powershell

      - name: Verify container
        run: docker ps

      - name: Verify bind mount
        run: docker inspect mywebapp-container